services:

  g6:
    container_name: g6
    build:
      context: .
    ports:
      - 9070:9070
    extra_hosts:
      - host.docker.internal:host-gateway

  ng:
    container_name: ng
    build:
      context: ./nginx
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - g6
